# Generated by Django 4.1 on 2022-11-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booksbase',
            fields=[
                ('BookId', models.AutoField(primary_key=True, serialize=False)),
                ('BookName', models.CharField(max_length=500)),
                ('BookPrice', models.CharField(max_length=500)),
                ('BookpicName', models.CharField(max_length=500)),
            ],
        ),
    ]
